//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cconvert.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class logindetail
    {
        public long id { get; set; }
        public long sourceid { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> logindatetime { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
